### ISSUE TITLE
Extracting values from TEI docs

### ISSUE THREAD

**Issue by ttasovac** [raffazizzi/gatsby-theme-ceteicean#1]
Hi Raff! Thank you again for bringing TEI to the Gatsby world! 

I was wondering about how one could extract values from a TEI doc to use in components. Let's say I have a SEO component and I want to use it together with my main Ceteicean.js component like this:

```js
const MyCeteicean = ({pageContext}) => {

  const routes = {
    "tei-tei": Tei,
    "tei-teiheader": TeiHeader,
    "tei-note": Note,
    "tei-placename": PlaceName,
    "tei-pb": (props) => <Pb {...props}/>,
  }

  return (
    <>
      <Layout>
        <Ceteicean pageContext={pageContext} routes={routes} />
      </Layout>
      <Seo title="xxx"></Seo>
    </>
  )

}

export default MyCeteicean
```

How could I extract the title from `/TEI/teiHeader/fileDesc/titleStmt/title[@type='main']` in order to use it in my SEO component? 

Many thanks in advance!

**Comment by raffazizzi** [comment]
Hi @ttasovac, you'll have to get access to the TEI DOM somehow. I can think of three possible approaches.

**1. Handle `<Seo>` in the Tei component.**

The `<TEI>` element is passed through the props, so you can look up the title from there. TEI is fairly top level so you may still be able to make `<Seo>` work, but it depends on your implementation.

```jsx
const Tei = (props) => {
  const el = props.teiNode as Element
  const title = el.querySelector("tei-teiHeader > tei-fileDesc > tei-titleStmt > tei-title[type='main']").textContent
  
  return (
      <>
        <Seo title={title} />
        <SafeUnchangedNode {...props} />
      </>
     )
}
```

If you need the default behavior of the Tei component provided in `gatsby-theme-ceteicean` (which deals with footnotes, for example), you may have to re-implement it, or wrap it somehow.

*Pros*: relies on the DOM already exposed by the routing of TEI elements to React components.
*Cons*: creates additional client-side traversing; may not work for all Seo configurations. 

**2. Retrieve the title (and other useful metadata) in `gatsby-node.js` and pass it to the `pageContext`**

Since this code runs on node rather than the browser, you'll have to provide your own DOM library. I recommend [xmldom](https://www.npmjs.com/package/xmldom) or [jsdom](https://www.npmjs.com/package/jsdom) (I prefer the latter because it supports query selectors, but it has a bit more overhead).

```js
exports.createPages = async ({ actions, graphql, reporter }) => {
  const { createPage } = actions
  await makeTeiPages(createPage, reporter, graphql)
}

async function makeTeiPages(createPage, reporter, graphql) {
  const component = require.resolve(`./src/gatsby-theme-ceteicean/components/Ceteicean.jsx`)

  const result = await graphql(`
    query {
      allCetei {
        nodes {
          prefixed
          elements
          parent {
            ... on File {
              name
            }
          }
        }
      }
    }
  `)
  if (result.errors) {
    reporter.panicOnBuild(`Error while running GraphQL query.`)
    return
  }

  for (const node of result.data.allCetei.nodes) {
    const name = node.parent.name

   // parse the document, e.g. with jsdom
    const jdom = new JSDOM(node.prefixed, {contentType: 'text/xml'})
    const doc = jdom.window.document

   // grab all the metadata you need
    const title = doc.querySelector("tei-fileDesc > tei-titleStmt > tei-title[type='main']").textContent

    createPage({
      path: name,
      component,
      context: {
        name,
        title,
        prefixed: node.prefixed,
        elements: node.elements
      }
    })
  }
}
```

*Pros*: DOM traversing happens only at build time, avoiding it on the client.
*Cons*: may introduce the need for a new dependency (though gatsby-theme-ceteicean already installs xmldom); may slow down build times if there are many TEI files

**3. Use regex at your own risk**

`pageContext` contains the raw CETEIcean data in `pageContext.prefixed`. You could look for the string that you need in there....

```js
pageContext.prefixed.match(/type="main">(.*?)<\/tei-title/)
```

*pros*: no DOM needed; can be performed in Ceteicean.tsx.
*cons*: risky! not always applicable.

You could also parse `pageContext.prefixed` with the browser's `DOMParser`, but I really don't recommend it.

**Comment by ttasovac** [comment]
Thanks a lot for the detailed write-up @raffazizzi!  

I've decided to go for option 2. I have tested it with both xmldom and jsdom, but ultimately settled on [libxmljs](https://github.com/libxmljs/libxmljs). 

I don't have the time to do any actual benchmarking, but libxmljs _should_ be faster than jsdom (because it's not a pure JS implementation, it only provides bindings for libxml2, which is written in C) + it makes my XPath fanatic's heart sing with joy that I can do something like this:

```js
const doc = libxmljs.parseXml(node.prefixed)
const title = doc.get('//tei-titleStmt/tei-title[@type="main"]') 
```

Happy times! 🤓
